### ISSUE TITLE
ERROR: Fatal error in method 'run!': can't modify frozen NilClass

### ISSUE THREAD

**Issue by LStuker** [InWork/queue_dispatcher#7]
When I start a new task I get the following error, with queue_dispatcher version "2.5.2"

```
  /Users/myname/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/queue_dispatcher-b3addf0ba342/lib/queue_dispatcher/acts_as_task_queue.rb:293:in `run!'
  script/queue_worker_dispatcher:221:in `worker_runner'
  script/queue_worker_dispatcher:185:in `block in spawn_and_monitor_workers'
  /Users/myname/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spawnling-2.1.6/lib/spawnling.rb:122:in `block in run'
  /Users/myname/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spawnling-2.1.6/lib/spawnling.rb:184:in `block in fork_it'
  /Users/myname/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spawnling-2.1.6/lib/spawnling.rb:160:in `fork'
  /Users/myname/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spawnling-2.1.6/lib/spawnling.rb:160:in `fork_it'
  /Users/myname/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spawnling-2.1.6/lib/spawnling.rb:122:in `run'
  /Users/myname/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spawnling-2.1.6/lib/spawnling.rb:102:in `initialize'
  script/queue_worker_dispatcher:184:in `new'
  script/queue_worker_dispatcher:184:in `spawn_and_monitor_workers'
  script/queue_worker_dispatcher:128:in `daemon_runner'
  script/queue_worker_dispatcher:158:in `daemon_start'
  script/queue_worker_dispatcher:281:in `<main>'
```

The error is caused when no @engine instance variable is set. My debugging showed that the if statement in https://github.com/InWork/queue_dispatcher/blob/6e8e9f5c132a0fada79556be7672df0903696142/lib/queue_dispatcher/acts_as_task_queue.rb#L293 is not correct, which came with the commit  d2f9e3a7d259653bc278f5d7dd54ce92f35e5d1d.

See debuggin:
```
puts "oh no" if defined? @engine
=> nil
[9] pry(#<TaskQueue>)> puts "oh no" if defined? @engine && @engine.methods.include?(:logger=)
oh no
```

The correct statement should be 
```
pry(#<TaskQueue>)> puts "oh no" if (defined? @engine) && (@engine.methods.include?(:logger=))
=> nil
```

**Comment by philkman** [comment]
Hallo Lucien

Ich hab den Fehler gefixt. Habe dann aber gesehen, dass Du diesen bereits Dir selbst zugewiesen hattest. Ich habe das Ticket geschlossen, aber allenfalls musst du es halt nochmals eröffnen.

Gruss
Philip
_____________________________________________________________________
Philip Kurmann
Senior Consultant
peaq GmbH                                 Mobile: +41 - 78 - 793 1810
Wiesenstrasse 44                         Mail: philip.kurmann@peaq.ch <mailto:philip.kurmann@peaq.ch>
CH-8954 Geroldswil                           Web:  http://www.peaq.ch <http://www.peaq.ch/>
_____________________________________________________________________

**Comment by LStuker** [comment]
Ja ich habs in meinen Branch auch schon angepasst, aber noch nicht gepushed.
Trotzdem merci für die schnelle fixen. :+1:
